# Generated by Django 4.2 on 2024-07-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_blogpost_image_alter_blogpost_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
