# Generated by Django 4.2 on 2024-07-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailings", "0003_alter_mailing_owner_alter_message_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="periodicity",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(max_length=10),
        ),
    ]
