# Generated by Django 4.2 on 2024-07-27 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mailings", "0004_alter_mailing_message_alter_mailing_periodicity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mailings.message"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                    ("MONTHLY", "Monthly"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("SCHEDULED", "Scheduled"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
    ]
