# Generated by Django 4.2 on 2024-07-27 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailings", "0005_alter_mailing_message_alter_mailing_periodicity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_mailings", "Can view mailings"),
                    ("can_disable_mailings", "Can disable mailings"),
                ]
            },
        ),
    ]
