# Generated by Django 4.2 on 2024-07-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailings", "0006_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("SCHEDULED", "Scheduled"),
                    ("DISABLED", "Disabled"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
    ]
